#!/usr/bin/env bash
# Provisions MiniStack for the wallet service: FIFO queues with redrive to
# their DLQs, the input queue policy (only the provider accounts may send),
# and least-privilege IAM users for the consumer and the publisher. IAM access
# keys are generated by MiniStack, so they are written to CREDENTIALS_OUT as
# an AWS shared credentials file (profiles wallet-consumer, wallet-publisher,
# provider-a and provider-b). Safe to re-run.
set -euo pipefail
: "${MINISTACK_ENDPOINT:?}" "${CREDENTIALS_OUT:?}"
export AWS_DEFAULT_REGION=us-east-1 AWS_PAGER="" AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test
awsm() { aws --endpoint-url "$MINISTACK_ENDPOINT" "$@"; }
cd "$(dirname "$0")"

awsm sqs create-queue --queue-name wager-transactions-dlq.fifo --attributes file://dlq.json >/dev/null
awsm sqs create-queue --queue-name wallet-events-dlq.fifo --attributes file://dlq.json >/dev/null
awsm sqs create-queue --queue-name wager-transactions.fifo --attributes file://wager-transactions.json >/dev/null
awsm sqs create-queue --queue-name wallet-events.fifo --attributes file://wallet-events.json >/dev/null
input_url=$(awsm sqs get-queue-url --queue-name wager-transactions.fifo --query QueueUrl --output text)
awsm sqs set-queue-attributes --queue-url "$input_url" --attributes file://wager-transactions-policy.json

# ensure_user NAME: creates the user if needed, (re)applies its policy, rotates
# its access key and prints "KEY SECRET".
ensure_user() {
  local name=$1
  awsm iam get-user --user-name "$name" >/dev/null 2>&1 || awsm iam create-user --user-name "$name" >/dev/null
  awsm iam put-user-policy --user-name "$name" --policy-name "$name" --policy-document "file://$name-policy.json"
  for key in $(awsm iam list-access-keys --user-name "$name" --query 'AccessKeyMetadata[].AccessKeyId' --output text); do
    awsm iam delete-access-key --user-name "$name" --access-key-id "$key"
  done
  awsm iam create-access-key --user-name "$name" --query 'AccessKey.[AccessKeyId,SecretAccessKey]' --output text
}

read -r consumer_key consumer_secret <<<"$(ensure_user wallet-consumer)"
read -r publisher_key publisher_secret <<<"$(ensure_user wallet-publisher)"

mkdir -p "$(dirname "$CREDENTIALS_OUT")"
tmp="$CREDENTIALS_OUT.tmp"
cat >"$tmp" <<EOT
[wallet-consumer]
aws_access_key_id = $consumer_key
aws_secret_access_key = $consumer_secret

[wallet-publisher]
aws_access_key_id = $publisher_key
aws_secret_access_key = $publisher_secret

# Providers use the root credential of their own account (MiniStack denies
# cross-account sends by IAM users; see ARCHITECTURE.md).
[provider-a]
aws_access_key_id = 111111111111
aws_secret_access_key = provider-a-secret

[provider-b]
aws_access_key_id = 222222222222
aws_secret_access_key = provider-b-secret
EOT
chmod 644 "$tmp"
mv "$tmp" "$CREDENTIALS_OUT"
echo "ministack provisioned; credentials at $CREDENTIALS_OUT"
