#!/usr/bin/env bash
# Provisions MiniStack for the wallet service: FIFO queues with redrive to
# their DLQs, the input queue policy (only the provider accounts may send),
# and least-privilege IAM users for the consumer and the publisher. IAM access
# keys are generated by MiniStack, so they are written to CREDENTIALS_OUT as
# an AWS shared credentials file (profiles wallet-consumer, wallet-publisher,
# provider-a and provider-b). Safe to re-run: existing IAM keys are kept.
set -euo pipefail
shopt -s inherit_errexit
: "${MINISTACK_ENDPOINT:?}" "${CREDENTIALS_OUT:?}"
export AWS_DEFAULT_REGION=us-east-1 AWS_PAGER="" AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test
awsm() { aws --endpoint-url "$MINISTACK_ENDPOINT" "$@"; }
cd "$(dirname "$0")"

awsm sqs create-queue --queue-name wager-transactions-dlq.fifo --attributes file://dlq.json >/dev/null
awsm sqs create-queue --queue-name wallet-events-dlq.fifo --attributes file://dlq.json >/dev/null
awsm sqs create-queue --queue-name wager-transactions.fifo --attributes file://wager-transactions.json >/dev/null
awsm sqs create-queue --queue-name wallet-events.fifo --attributes file://wallet-events.json >/dev/null
input_url=$(awsm sqs get-queue-url --queue-name wager-transactions.fifo --query QueueUrl --output text)
awsm sqs set-queue-attributes --queue-url "$input_url" --attributes file://wager-transactions-policy.json

# profile_creds NAME: prints "KEY SECRET" of profile NAME in CREDENTIALS_OUT
# (the file this script writes), or nothing if the file or profile is missing.
profile_creds() {
  [ -f "$CREDENTIALS_OUT" ] || return 0
  awk -v p="[$1]" '
    /^\[/ { in_p = ($0 == p); next }
    in_p && $1 == "aws_access_key_id" { k = $3 }
    in_p && $1 == "aws_secret_access_key" { s = $3 }
    END { if (k != "" && s != "") print k, s }
  ' "$CREDENTIALS_OUT"
}

# ensure_user NAME: creates the user if needed, (re)applies its policy and
# prints "KEY SECRET". An access key already recorded in CREDENTIALS_OUT that
# MiniStack still lists is kept (running replicas hold it); otherwise stale
# keys are deleted and a new one is created.
ensure_user() {
  local name=$1 saved saved_key saved_secret listed key
  saved=$(profile_creds "$name")
  awsm iam get-user --user-name "$name" >/dev/null 2>&1 || awsm iam create-user --user-name "$name" >/dev/null
  awsm iam put-user-policy --user-name "$name" --policy-name "$name" --policy-document "file://$name-policy.json"
  listed=$(awsm iam list-access-keys --user-name "$name" --query 'AccessKeyMetadata[].AccessKeyId' --output text)
  if [ -n "$saved" ]; then
    read -r saved_key saved_secret <<<"$saved"
    for key in $listed; do
      if [ "$key" = "$saved_key" ]; then
        echo "$saved_key $saved_secret"
        return 0
      fi
    done
  fi
  for key in $listed; do
    awsm iam delete-access-key --user-name "$name" --access-key-id "$key"
  done
  awsm iam create-access-key --user-name "$name" --query 'AccessKey.[AccessKeyId,SecretAccessKey]' --output text
}

out=$(ensure_user wallet-consumer)
read -r consumer_key consumer_secret <<<"$out"
out=$(ensure_user wallet-publisher)
read -r publisher_key publisher_secret <<<"$out"
for v in "$consumer_key" "$consumer_secret" "$publisher_key" "$publisher_secret"; do
  if [ -z "$v" ]; then echo "empty IAM access key or secret; refusing to write credentials" >&2; exit 1; fi
done

mkdir -p "$(dirname "$CREDENTIALS_OUT")"
tmp="$CREDENTIALS_OUT.tmp"
cat >"$tmp" <<EOT
[wallet-consumer]
aws_access_key_id = $consumer_key
aws_secret_access_key = $consumer_secret

[wallet-publisher]
aws_access_key_id = $publisher_key
aws_secret_access_key = $publisher_secret

# Providers use the root credential of their own account (MiniStack denies
# cross-account sends by IAM users; see ARCHITECTURE.md).
[provider-a]
aws_access_key_id = 111111111111
aws_secret_access_key = provider-a-secret

[provider-b]
aws_access_key_id = 222222222222
aws_secret_access_key = provider-b-secret
EOT
chmod 644 "$tmp"
mv "$tmp" "$CREDENTIALS_OUT"
echo "ministack provisioned; credentials at $CREDENTIALS_OUT"
